apiVersion: v1
kind: Secret
metadata:
  name: k8s-ca-secret
  namespace: cert-manager
type: kubernetes.io/tls
data:
  tls.crt: <base64 of k8s-ca.crt>
  tls.key: <base64 of k8s-ca.key>


# Usually:
cat /etc/kubernetes/pki/ca.crt > k8s-ca.crt
cat /etc/kubernetes/pki/ca.key > k8s-ca.key

You need both the cert and the private key.
⚠️ Never expose ca.key publicly — this is sensitive.
